-- EJECUTA TODO ESTE SCRIPT EN EL 'SQL EDITOR' DE SUPABASE

-- 1. TABLA: registros (Usuarios)
create table if not exists public.registros (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nombre text not null,
  telefono text not null
);

-- 2. TABLA: fichajes (Control de Asistencia)
create table if not exists public.fichajes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  usuario_id bigint references public.registros(id) on delete cascade,
  fecha_evento timestamp with time zone default timezone('utc'::text, now()),
  tipo text not null -- 'INGRESO' o 'SALIDA'
);

-- 3. TABLA: logs_registro (Auditoría opcional)
create table if not exists public.logs_registro (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  fecha_registro timestamp with time zone,
  accion text
);

-- 4. SEGURIDAD: Habilitar RLS (Row Level Security)
alter table public.registros enable row level security;
alter table public.fichajes enable row level security;
alter table public.logs_registro enable row level security;

-- 5. LIMPIEZA: Borrar políticas antiguas para evitar conflictos
drop policy if exists "Politica Publica Registros" on public.registros;
drop policy if exists "Politica Publica Fichajes" on public.fichajes;
drop policy if exists "Politica Publica Logs" on public.logs_registro;

-- Borrar políticas de versiones anteriores si existen
drop policy if exists "Permitir todo publico registros" on public.registros;
drop policy if exists "Permitir todo publico fichajes" on public.fichajes;
drop policy if exists "Permitir todo publico logs" on public.logs_registro;

-- 6. PERMISOS: Crear políticas de acceso total (Lectura/Escritura pública para la demo)
create policy "Politica Publica Registros"
on public.registros for all using (true) with check (true);

create policy "Politica Publica Fichajes"
on public.fichajes for all using (true) with check (true);

create policy "Politica Publica Logs"
on public.logs_registro for all using (true) with check (true);